name: First Workflow
on: push
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: print greeting
        run: echo "Hello world!"
      - name: install node version 16
        uses: actions/setup-node@v4
        with:
          node-version-file: 14
      - name: node version
        run: echo $(node -v)
      - name: print bye
        run: echo "Bye Bye!"
#
