name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: print greeting
        run: echo "Hello world!"
      - name: node version
        run: echo $(node -v)
      - name: print bye
        run: echo "Bye Bye!"
#
